// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvwcchkwGXwRj3mFMRYxIunPNCeDFxpqU',
    appId: '1:273490264401:web:0399c777b626d285301370',
    messagingSenderId: '273490264401',
    projectId: 'flash-chat-fcb60',
    authDomain: 'flash-chat-fcb60.firebaseapp.com',
    storageBucket: 'flash-chat-fcb60.appspot.com',
    measurementId: 'G-05299K5W3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHBp0quNoMliTPclj00-U1e4NMl57NIw',
    appId: '1:273490264401:android:06930824ea36c485301370',
    messagingSenderId: '273490264401',
    projectId: 'flash-chat-fcb60',
    storageBucket: 'flash-chat-fcb60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIyU1uYRCizddkhG48FBTHpS6dhzPtwE',
    appId: '1:273490264401:ios:dac5f61b88497702301370',
    messagingSenderId: '273490264401',
    projectId: 'flash-chat-fcb60',
    storageBucket: 'flash-chat-fcb60.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIyU1uYRCizddkhG48FBTHpS6dhzPtwE',
    appId: '1:273490264401:ios:dac5f61b88497702301370',
    messagingSenderId: '273490264401',
    projectId: 'flash-chat-fcb60',
    storageBucket: 'flash-chat-fcb60.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvwcchkwGXwRj3mFMRYxIunPNCeDFxpqU',
    appId: '1:273490264401:web:f57701d71bfb2c19301370',
    messagingSenderId: '273490264401',
    projectId: 'flash-chat-fcb60',
    authDomain: 'flash-chat-fcb60.firebaseapp.com',
    storageBucket: 'flash-chat-fcb60.appspot.com',
    measurementId: 'G-GBW6FXB1L3',
  );
}
